#!/usr/bin/env node
/**
 * Regenerates TOOLS.md from the live server's tools/list, so the reference cannot drift from
 * what the server actually serves.
 *
 *   node scripts/sync-tools.mjs                         # https://adexto.xyz/api/mcp
 *   MCP_URL=http://127.0.0.1:3000/api/mcp node scripts/sync-tools.mjs
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const MCP_URL = process.env.MCP_URL || "https://adexto.xyz/api/mcp";
const OUT = fileURLToPath(new URL("../TOOLS.md", import.meta.url));

let nextId = 0;
async function rpc(method, params = {}) {
  const res = await fetch(MCP_URL, {
    method: "POST",
    headers: { "content-type": "application/json", accept: "application/json, text/event-stream" },
    body: JSON.stringify({ jsonrpc: "2.0", id: ++nextId, method, params }),
    signal: AbortSignal.timeout(60_000),
  });
  const text = await res.text();
  const data = text.split("\n").filter((l) => l.startsWith("data:")).map((l) => l.slice(5).trim());
  const msg = JSON.parse(data.length ? data[data.length - 1] : text);
  if (msg.error) throw new Error(`${method}: ${msg.error.message}`);
  return msg.result;
}

function typeOf(schema) {
  if (!schema || typeof schema !== "object") return "any";
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (Array.isArray(schema.anyOf)) return schema.anyOf.map(typeOf).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.join(" | ");
  if (schema.type === "array") return `${typeOf(schema.items)}[]`;
  if (schema.type) return schema.type;
  return "any";
}

const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();

function kind(t) {
  const a = t.annotations ?? {};
  if (a.destructiveHint) return "spends money";
  if (a.readOnlyHint) return "read-only";
  return "writes";
}

const init = await rpc("initialize", {
  protocolVersion: "2025-11-25",
  capabilities: {},
  clientInfo: { name: "adexto-mcp-docs", version: "1.0.0" },
});
const { tools } = await rpc("tools/list");
const server = init.serverInfo ?? {};

const lines = [
  "# Tool reference",
  "",
  `Generated by \`scripts/sync-tools.mjs\` from \`${MCP_URL}\` (server ${server.name ?? "?"} ${server.version ?? "?"}). ` +
    "Do not edit by hand; run the script again instead.",
  "",
  `${tools.length} tools. Every tool returns its answer twice: as JSON text, and as \`structuredContent\` that matches ` +
    "its output schema. A refusal (for example `unknown_market`) is an ordinary answer with an `error` code, not a " +
    "protocol error, and nothing is spent when a tool refuses.",
  "",
  "| Tool | What it does | Kind |",
  "|---|---|---|",
  ...tools.map((t) => `| [\`${t.name}\`](#${t.name}) | ${cell(t.title ?? "")} | ${kind(t)} |`),
  "",
];

for (const t of tools) {
  lines.push(`## ${t.name}`, "", `**${cell(t.title ?? t.name)}** · ${kind(t)}`, "", t.description ?? "", "");
  const props = t.inputSchema?.properties ?? {};
  const required = new Set(t.inputSchema?.required ?? []);
  if (Object.keys(props).length === 0) {
    lines.push("Input: none.", "");
  } else {
    lines.push("| Input | Type | Required | Description |", "|---|---|---|---|");
    for (const [name, schema] of Object.entries(props)) {
      lines.push(`| \`${name}\` | ${cell(typeOf(schema))} | ${required.has(name) ? "yes" : "no"} | ${cell(schema.description)} |`);
    }
    lines.push("");
  }
  const out = t.outputSchema?.properties ?? {};
  if (Object.keys(out).length > 0) {
    lines.push("| Output field | Type | Description |", "|---|---|---|");
    for (const [name, schema] of Object.entries(out)) {
      lines.push(`| \`${name}\` | ${cell(typeOf(schema))} | ${cell(schema.description)} |`);
    }
    lines.push("");
  }
}

writeFileSync(OUT, `${lines.join("\n").trim()}\n`);
console.log(`Wrote ${OUT}: ${tools.length} tools from ${MCP_URL}`);
